TEMPLATE_NAME=generic
MACHINE=
SCRIPT_NAME=aap
EXTRA_EM_FILE=genelf
OUTPUT_FORMAT="elf32-aap"
NO_REL_RELOCS=yes
TEXT_START_ADDR=0x0100
ARCH=aap
ENTRY=_start
MAXPAGESIZE=1
EMBEDDED=yes
ELFSIZE=32
ALIGNMENT=4
NOP=0x0000
OTHER_SYMBOLS='PROVIDE (__stack = 0x200000);'
